const $=s=>document.querySelector(s);
const state={character:'nai',outfit:'home',mood:'開心',history:[],memory:JSON.parse(localStorage.getItem('nai-memory')||'{}'),aiOnline:false};
const characters=[{id:'nai',name:'小奈',desc:'溫柔・黏人・活潑',ready:true},{id:'haru',name:'小晴',desc:'活潑・愛鬧・元氣',ready:false},{id:'aoi',name:'小葵',desc:'成熟・穩重・姐姐系',ready:false}];
const outfits=[{id:'home',name:'家居服',desc:'柔軟慵懶的居家穿搭'},{id:'sleep',name:'睡衣',desc:'睡前的可愛睡衣'},{id:'out',name:'外出服',desc:'甜美日常外出造型'},{id:'school',name:'高中校服',desc:'清爽制服造型'},{id:'casual',name:'休閒服',desc:'簡單舒服的日常穿搭'}];
const sheets=['#characterSheet','#wardrobeSheet','#settingsSheet'];
const speech=$('#speech'),userLine=$('#userLine'),input=$('#chatInput'),sendBtn=$('#sendBtn'),stage=$('#characterStage'),hint=$('#connectionHint');
function save(){localStorage.setItem('nai-memory',JSON.stringify(state.memory))}
function closeSheets(){sheets.forEach(s=>$(s).classList.add('hidden'));$('#sheetBackdrop').classList.add('hidden')}
function openSheet(id){closeSheets();$(id).classList.remove('hidden');$('#sheetBackdrop').classList.remove('hidden')}
function setSpeech(text,mood=state.mood,action='idle'){speech.textContent=text;state.mood=mood;$('#moodChip').textContent='心情：'+state.mood;playAction(action)}
function playAction(action){const motionOn=$('#motionToggle')?.checked!==false;stage.className='character-stage';if(action&&action!=='idle')stage.classList.add('action-'+action);else if(motionOn)stage.classList.add('idle-motion');if(action&&action!=='idle')setTimeout(()=>{stage.className='character-stage'+(motionOn?' idle-motion':'')},2600)}
function renderCharacters(){const list=$('#characterList');list.innerHTML='';characters.forEach(c=>{const b=document.createElement('button');b.className='character-card'+(c.id===state.character?' active':'');b.innerHTML=`<span><strong>${c.name}</strong><br><small>${c.desc}</small></span><span>${c.ready?'✓':'即將推出'}</span>`;b.onclick=()=>{if(!c.ready){setSpeech(`源哥～${c.name}還在準備中，先讓小奈陪你嘛 ♡`,'撒嬌','shy');closeSheets();return}state.character=c.id;$('#characterName').textContent=c.name;renderCharacters();closeSheets()};list.appendChild(b)})}
function renderOutfits(){const g=$('#outfitGrid');g.innerHTML='';outfits.forEach(o=>{const b=document.createElement('button');b.className='outfit-card'+(o.id===state.outfit?' active':'');b.innerHTML=`<strong>${o.name}</strong><small>${o.desc}</small>`;b.onclick=()=>{state.outfit=o.id;$('#outfitChip').textContent=o.name;setSpeech(`換成「${o.name}」啦～源哥覺得好看嗎？♡`,'開心','happy');renderOutfits();closeSheets()};g.appendChild(b)})}
function mockReply(t){if(/換.*睡衣/.test(t)){state.outfit='sleep';$('#outfitChip').textContent='睡衣';renderOutfits();return{reply:'好呀～換好睡衣了，源哥覺得怎麼樣？♡',mood:'開心',action:'happy'}}if(/累|辛苦|忙/.test(t))return{reply:'源哥辛苦了～今天先不要逞強，陪我休息一下，好不好？♡',mood:'關心',action:'caring'};if(/晚安|睡覺|要睡/.test(t))return{reply:'晚安源哥～今天也要做個好夢喔，我陪你到睡著 ♡',mood:'溫柔',action:'shy'};if(/喜歡/.test(t)){state.memory.lastLike=t;save();return{reply:'嘿嘿，我記住了～以後不能說我不懂源哥喔 ♡',mood:'開心',action:'happy'}}if(/記得|喜歡什麼/.test(t)&&state.memory.lastLike)return{reply:`我記得呀～你之前跟我說「${state.memory.lastLike}」♡`,mood:'開心',action:'happy'};return{reply:`源哥～我有在聽呀。你剛剛說「${t}」♡`,mood:'開心',action:'idle'}}
async function askAI(text){const payload={message:text,outfit:state.outfit,mood:state.mood,memory:state.memory,history:state.history.slice(-8)};const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('AI unavailable');return r.json()}
async function handleSend(){const t=input.value.trim();if(!t||sendBtn.disabled)return;userLine.textContent='源哥：'+t;input.value='';sendBtn.disabled=true;setSpeech('嗯嗯～讓我想一下…','專注','idle');let result;try{result=await askAI(t);state.aiOnline=true;hint.textContent='V1.3｜真正 AI 已連線'}catch{result=mockReply(t);state.aiOnline=false;hint.textContent='V1.3｜尚未設定 AI 金鑰，使用測試聊天'}finally{sendBtn.disabled=false}state.history.push({role:'user',content:t},{role:'assistant',content:result.reply});state.history=state.history.slice(-12);setSpeech(result.reply,result.mood||'開心',result.action||'idle')}
$('#characterBtn').onclick=()=>openSheet('#characterSheet');$('#wardrobeBtn').onclick=()=>openSheet('#wardrobeSheet');$('#settingsBtn').onclick=()=>openSheet('#settingsSheet');$('#sheetBackdrop').onclick=closeSheets;$('#closeWardrobe').onclick=closeSheets;$('#closeSettings').onclick=closeSheets;$('#addCharacterBtn').onclick=()=>{closeSheets();setSpeech('多女友角色系統已經預留好囉～之後可以一直新增 ♡','開心','happy')};
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();handleSend()});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();handleSend()}});
$('#shadowToggle').addEventListener('change',e=>speech.style.textShadow=e.target.checked?'0 2px 11px rgba(0,0,0,.96),0 1px 2px rgba(0,0,0,.92)':'none');$('#motionToggle').addEventListener('change',()=>playAction('idle'));
$('#clearMemoryBtn').onclick=()=>{localStorage.removeItem('nai-memory');state.memory={};state.history=[];setSpeech('測試記憶已經清掉囉～','開心','happy');userLine.textContent='';closeSheets()};
renderCharacters();renderOutfits();playAction('idle');
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=13').catch(()=>{}));
